spring.application.name=consumer
server.port=8081
spring.rabbitmq.addresses=amqps://sjxafqaj:lUmCPRkPnyRzUtRFvxWkQO6fCVpp_3W6@mustang.rmq.cloudamqp.com/sjxafqaj
rabbitmq.queue.notification=notification.queue